<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\bishop_black.png" />
    <None Remove="Resources\Images\bishop_white.png" />
    <None Remove="Resources\Images\idea.png" />
    <None Remove="Resources\Images\king_black.png" />
    <None Remove="Resources\Images\king_white.png" />
    <None Remove="Resources\Images\knight_black.png" />
    <None Remove="Resources\Images\knight_white.png" />
    <None Remove="Resources\Images\pawn_black.png" />
    <None Remove="Resources\Images\pawn_white.png" />
    <None Remove="Resources\Images\queen_black.png" />
    <None Remove="Resources\Images\queen_white.png" />
    <None Remove="Resources\Images\reverse.png" />
    <None Remove="Resources\Images\rook_black.png" />
    <None Remove="Resources\Images\rook_white.png" />
    <None Remove="View\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Images\bishop_black.png" />
    <EmbeddedResource Include="Resources\Images\bishop_white.png" />
    <EmbeddedResource Include="Resources\Images\idea.png" />
    <EmbeddedResource Include="Resources\Images\king_black.png" />
    <EmbeddedResource Include="Resources\Images\king_white.png" />
    <EmbeddedResource Include="Resources\Images\knight_black.png" />
    <EmbeddedResource Include="Resources\Images\knight_white.png" />
    <EmbeddedResource Include="Resources\Images\pawn_black.png" />
    <EmbeddedResource Include="Resources\Images\pawn_white.png" />
    <EmbeddedResource Include="Resources\Images\queen_black.png" />
    <EmbeddedResource Include="Resources\Images\queen_white.png" />
    <EmbeddedResource Include="Resources\Images\reverse.png" />
    <EmbeddedResource Include="Resources\Images\rook_black.png" />
    <EmbeddedResource Include="Resources\Images\rook_white.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Grandmasters\alireza-firouzja.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\andrew-tang.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\arjun-erigaisi.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\fabiano-caruana.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\gukesh-dommaraju.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\hikaru-nakamura.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\jan-krzysztof-duda.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\magnus-carlsen.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\nodirbek-abdusattorov.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\praggnanandhaa-rameshbabu.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\wei-yi.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Grandmasters\wesley-so.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
